# -----------------------------------------------------------------------------
# This file is part of the xPack distribution.
#   (https://xpack.github.io)
# Copyright (c) 2021 Liviu Ionescu.
#
# Permission to use, copy, modify, and/or distribute this software
# for any purpose is hereby granted, under the terms of the MIT license.
# -----------------------------------------------------------------------------

# https://help.github.com/en/actions
# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
# https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_dispatch
# https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event

# -----------------------------------------------------------------------------


name: 'Test diag-trace on all platforms'

on:
  workflow_dispatch:

jobs:

  linux-x64:
    name: 'Linux x64 tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Machine'
        run: uname -a
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 3
          submodules: true
      - name: 'Ubuntu latest x64 native xpm test-all'
        run: bash tests/scripts/test-all.sh
      - name: 'Debian docker xpm test-all'
        uses: docker://node:lts
        with:
          entrypoint: /bin/bash
          args: /github/workspace/tests/scripts/test-all.sh --image node:lts
      # - name: 'Ubuntu 20.04 x64 docker xpm test-all'
      #   uses: docker://ubuntu:20.04
      #   with:
      #     entrypoint: /bin/bash
      #     args: /github/workspace/tests/scripts/test-all.sh --image ubuntu:20.04
      # - name: 'Ubuntu 18.04 x64 docker xpm test-all'
      #   uses: docker://ubuntu:18.04
      #   with:
      #     entrypoint: /bin/bash
      #     args: /github/workspace/tests/scripts/test-all.sh --image ubuntu:18.04

  linux-arm64:
    name: 'Linux arm64 tests'
    runs-on: [self-hosted, linux, arm64]
    steps:
      - name: 'Machine'
        run: uname -a
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 3
          submodules: true
      - name: 'Raspberry Pi OS arm64 native xpm test-all'
        run: bash tests/scripts/test-all.sh
      # - name: 'Ubuntu 20.04 docker xpm test-all'
      #   uses: docker://ubuntu:20.04
      #   with:
      #     entrypoint: /bin/bash
      #     args: /github/workspace/tests/scripts/test-all.sh --image ubuntu:20.04
      - name: 'Debian docker xpm test-all'
        uses: docker://node:lts
        with:
          entrypoint: /bin/bash
          args: /github/workspace/tests/scripts/test-all.sh --image node:lts
      # - name: 'Debian buster docker xpm test-all'
      #   uses: docker://debian:buster
      #   with:
      #     entrypoint: /bin/bash
      #     args: /github/workspace/tests/scripts/test-all.sh --image debian:buster

  linux-arm32:
    name: 'Linux arm32 tests'
    runs-on: [self-hosted, linux, arm64]
    steps:
      - name: 'Machine'
        run: uname -a
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 3
          submodules: true
      - name: 'Debian arm32 docker test'
        uses: docker://arm32v7/node:lts
        with:
          entrypoint: /usr/bin/linux32
          args: /bin/bash /github/workspace/tests/scripts/test-all.sh --image arm32v7/node:lts
      # Fails to install nvm
      # - name: 'Ubuntu 20.04 arm32 docker test'
      #   uses: docker://arm32v7/ubuntu:20.04
      #   with:
      #     entrypoint: /usr/bin/linux32
      #     args: /bin/bash /github/workspace/tests/scripts/test-all.sh --image arm32v7/ubuntu:20.04
      # Fails to install nvm
      # - name: 'Debian buster arm32 docker test'
      #   uses: docker://arm32v7/debian:buster
      #   with:
      #     entrypoint: /usr/bin/linux32
      #     args: /bin/bash /github/workspace/tests/scripts/test-all.sh --image arm32v7/debian:buster

  # macos-x64:
  #   name: 'macOS x64 tests'
  #   runs-on: macos-latest
  #   steps:
  #     - name: 'Machine'
  #       run: uname -a
  #     - name: 'Checkout'
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 3
  #         submodules: true
  #     - name: 'Run native xpm test-all'
  #       run: bash tests/scripts/test-all.sh

  # macos-arm64:
  #   name: 'macOS arm64 tests'
  #   runs-on: [self-hosted, macos, apple]
  #   defaults:
  #     run:
  #       shell: "/usr/bin/arch -arch arm64e /bin/bash -l {0}"
  #   steps:
  #     - name: 'Machine'
  #       run: uname -a
  #     - name: 'Checkout'
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 3
  #         submodules: true
  #     - name: 'Run native xpm test-all'
  #       run: bash tests/scripts/test-all.sh

  # windows-x64:
  #   name: 'Windows x64 tests'
  #   runs-on: windows-latest
  #   steps:
  #     - name: 'Machine'
  #       run: uname -a
  #     - name: 'Checkout'
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 3
  #         submodules: true
  #     - name: 'Run native xpm test-all'
  #       run: bash tests/scripts/test-all.sh

# -----------------------------------------------------------------------------
